schema_version = "1.0.0"
id = "export_iges"
version = "2.0.0"
name = "Export IGES"
tagline = "Export mesh data as Subdiv bi-cubic patches in IGES format"
maintainer = "Rajeev Nair"
type = "add-on"
website = "https://www.digital-sculptors.com/cms/index.php/software/blender-plugins/63-export-iges.html"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Digital Sculptors"]
platforms =  ["linux-x64"]
[permissions]
files = "Export IGES files to disk"