schema_version = "1.0.0"
id = "measure_and_scale"
version = "1.1.2"
name = "Measure and Scale"
tagline = "Measure and Scale object uniformaly"
maintainer = "Bill3D (Belaid ZIANE) belaiziane18@gmail.com"
type = "add-on"

# Minimum supported Blender versions
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-3.0-or-later",
]
tags = ["Modeling"]
