schema_version = "1.0.0"

id = "CAD_Sketcher"
version = "0.27.5"
name = "CAD Sketcher"
tagline = "Parametric, constraint-based geometry sketcher"
maintainer = "hlorus <dave19924@gmail.com>"
type = "add-on"

permissions = ["files", "network"]

website = "https://www.cadsketcher.com/"

tags = ["3D View", "Modeling", "Mesh", "Object"]

blender_version_min = "3.3.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
  "./wheels/py_slvs-1.0.6-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-manylinux_2_17_i686.manylinux2014_i686.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-musllinux_1_1_aarch64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-musllinux_1_1_i686.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-musllinux_1_1_x86_64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-win_amd64.whl",
  "./wheels/py_slvs-1.0.6-cp311-cp311-win32.whl",
]
