name: build_docs_test
on: 
  pull_request:
    branches: main
    paths: "docs/**"

jobs:
  test-build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Addon
        uses: actions/checkout@v3
        with:
          path: CAD_Sketcher

      - name: Checkout Blender Scripts
        uses: actions/checkout@v3
        with:
          repository: blender/blender
          path: blender-git
          submodules: "true"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r ./CAD_Sketcher/docs/requirements.txt

      - name: Set Pythonpath
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/blender-git/blender/release/scripts/modules:$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Build
        run: python3.10 -m mkdocs build -f ./docs/mkdocs.yml
        working-directory: ./CAD_Sketcher
